### ISSUE TITLE
Fluid capacity for fluid trains is still calculated at pre 2.0 values

### ISSUE THREAD

**Issue by Terrcha** [mamoniot/project-cybersyn#203] opened 2024-11-10 16:10 UTC
It seems that in 2.0 the fluid capacity for fluid wagons has increased from 25K to 50K, and it looks like trains are only getting dispatched to fluid stops if you half the amount of fluid the train can hold.

**Comment by NeveHanter** [comment] 2024-11-17 21:01
I have the same issue, in Pyanodon's mods the fluid wagons still have 25k capacity even if run on Space Age 2.0.19 (with Space Age mod disabled, but running its binary). I need to halve the request thresholds of what I usually used/expect for it to dispatch the train.

Example from my game:
I have a station that currently have 24297.5206 Formaldehyde stored.
My constant combinator is set to Formaldehyde -37500 and request threshold of 12500.
This added gives me 13202.4794 so its above the threshold so the train should be dispatched but it isn't.
If I set the request threshold to 6603 it won't be dispatched, but if I set it to 6602 then the train will be dispatched and it will have expected/correct order Formaldehyde >= 13204.

Another example:
I have an empty station (I disconnected the wires from tanks).
My constant combinator is set to Formaldehyde -37500 and request threshold of 25000 (I updated it so it's explicitly set to capacity of the full fluid wagon).
We have nothing at the station so we should expect it to request a train, but no train is being dispatched until I decrease request threshold to 12500. If I set it to 12501 (one above) then the network will try to request a train but it won't be able to because it will think there's no train that with enough capacity (even if I have a free train with 25k fluid wagon). **Note that again the train is dispatched with an expected/correct order Formaldehyde >= 25k.**

This worked fine in 1.1 save and stopped working after moving to Factorio 2.0.19 (Pyanodon's mods didn't change the fluid capacity between 1.1 and 2.0 compatible version of the mods).

**Comment by wcjohnson** [comment] 2024-11-19 21:05
I cannot reproduce this in a plain Space Age environment. Cybersyn appears to be perfectly aware that fluid wagons now hold 50k.

I also looked at the code and it uses `wagon.prototype.fluid_capacity` to determine fluid capacity -- which means it's being calculated directly from the prototype of the associated fluid wagon. This means it should work with modded fluid wagons as well. If it is not working with a modded fluid wagon, it's probably because the prototype still has the vanilla value of 50k. You'd have to check with the mod author on that.

I will need a reproduction save file with only Space Age + Cybersyn enabled in order to act further on this issue.

**Comment by wcjohnson** [comment] 2024-11-20 03:25
I had another thought. Cybersyn computes and caches cargo size whenever a train is built, or its rolling stock is changed. It has no way of knowing if an outside mod changes values for trains that are already built.

If a savegame was brought in from before these values were changed, it's possible they're stuck in cache. Try deconstructing and reconstructing a broken train and see if it fixes anything.

**Closed** 2024-11-20 14:06 UTC
